### ISSUE TITLE
Bug in RequiredAnyRole

### ISSUE THREAD

**Issue by AhmadShkour71** [RileCraft/DiscordBot-Template#10]
**Describe the issue**
When cheak RequiredAnyRole in command 
console he will tell me error __missing is not defined__

**Screenshots**
![Screenshot 2021-12-13 060732](https://user-images.githubusercontent.com/73717039/145750995-b18adc37-a79d-49f3-82d3-d067ff9835e4.jpg)
![Screenshot 2021-12-13 060742](https://user-images.githubusercontent.com/73717039/145750999-940bd5f4-097f-4eff-a7f9-5ff67e63fa79.jpg)

**Comment by RileCraft** [comment]
i must have forgotten to update the variable. This will be patched in next update.

**Comment by RileCraft** [comment]
Fixed in 4.0.8

**Comment by AhmadShkour71** [comment]
thx bro
