### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Arex69** [RileCraft/DiscordBot-Template#11]
I added my own guildMemberAdd.js event from a tutorial and tweaked it a little bit.
Code - https://pastebin.com/v5A6mxLV

![unknown](https://user-images.githubusercontent.com/74128329/146509300-fe477192-cb87-4150-81a6-e7aa0f19d2f8.png)
I then get this error.

I've contacted discord.js public support but they told me i didnt define my root in "loadEvents.js Line 16"
What should I do?
(and yes i know i mentioned "discord-js", I already corrected that)

**Comment by RileCraft** [comment]
give the guildMemberAdd file code and loadEvents code

**Comment by Arex69** [comment]
guildMemberAdd.js - https://pastebin.com/v5A6mxLV
loadEvents.js - https://pastebin.com/LQT7EreB

**Comment by RileCraft** [comment]
```js
module.exports = {
name: "guildMemberAdd",
run: async(member) => {
enter code
}
}
```

**Comment by Arex69** [comment]
Finally, my saviour. Thank you so much!
