### ISSUE TITLE
Slash Command don't load

### ISSUE THREAD

**Issue by Kae-Tempest** [RileCraft/DiscordBot-Template#14]
I juste clone the project, and change config.js but slash command doesn't load after 30 min

OS : Win 11
Node : 16.13.1

**Comment by RileCraft** [comment]
(1) Any error in console?
(2) Host issue.
(3) Bot doesn't have application commands permission.

**Comment by Kae-Tempest** [comment]
Any error un the console, bot have full permissions.

**Comment by RileCraft** [comment]
(1) Global commands can take upto a hour to fully update so it can be that

(2) If it's a guild command then make sure you provided valis guild Ids.

(3) Make sure in the slashCommand you filled all required options correctly.

(4) Check if the slashCommand is there in the `<client>.commands.slash` collection.

**Comment by Kae-Tempest** [comment]
It's good, it's take time for load
