### ISSUE TITLE
customizable prefix

### ISSUE THREAD

**Issue by gelones** [RileCraft/DiscordBot-Template#15]
You might as well make a system where we can change the bot prefix by command, so you can have a different prefix for each guild

**Comment by RileCraft** [comment]
That is your job lol. This is just like a basic template to start making a bot.

**Comment by gelones** [comment]
Could you at least say in which file I can make the customizable prefix? MessageCreate or LoadCommandOptions, please.

**Comment by gelones** [comment]
> That is your job lol. This is just like a basic template to start making a bot.

Could you at least say in which file I can make the customizable prefix? MessageCreate or LoadCommandOptions, please.
