### ISSUE TITLE
Suggestion Request

### ISSUE THREAD

**Issue by Kae-Tempest** [RileCraft/DiscordBot-Template#16]
It's possible, for you give us more info on you non client event, how it's work ?

it's for custom event, like one streamer up his stream and that mat an event or other thing ?

**Comment by RileCraft** [comment]
In custom events aka non client events you basically use the old style of creating a event i.e
```js
<anything>.on(<event name>, (args) => {
// Code
})
```
in the format
```js
module.exports = {
customEvent: true,
run: () => {
// Code i gave above
})
```
In the run() you can put `client, Discord` to access them as they are automatically passed through the handler. Everything else you have to do manually
