### ISSUE TITLE
customizable prefix in which file?

### ISSUE THREAD

**Issue by gelones** [RileCraft/DiscordBot-Template#20]
Could you at least say in which file I can make the customizable prefix? MessageCreate or LoadCommandOptions, please.

**Comment by RileCraft** [comment]
both

**Comment by gelones** [comment]
> both

but if I do both, it will bug

**Comment by RileCraft** [comment]
well like i said before thats on you and you have to figure something out

**Comment by gelones** [comment]
> well like i said before thats on you and you have to figure something out

yeah I tried, but I couldn't do it with a custom prefix

**Comment by RileCraft** [comment]
#¯\_(ツ)_/¯

**Comment by gelones** [comment]
> ¯_(ツ)_/¯

now i managed to make the custom prefix, thanks!
