### ISSUE TITLE
Ping command

### ISSUE THREAD

**Issue by Ruqen** [RileCraft/DiscordBot-Template#38]
**Describe the issue**
The ping command doesn't show actual results

**To Reproduce**
1. Use the ping command and watch the results

**Expected behavior**
Bot should give us the real ping and not unreal results

**Screenshots**
![image](https://user-images.githubusercontent.com/73693641/156930182-3cef646d-5b0a-46db-9466-8fdefedaded9.png)

**Host Details:**
 - OS: Windows
 - NodeJS Version: v16.14.0

**Additional context**
None

**Comment by RileCraft** [comment]
Are you on localhost

**Comment by Ruqen** [comment]
> Are you on localhost

Yes

**Comment by RileCraft** [comment]
It shows negative on localhost

**Comment by Ruqen** [comment]
> It shows negative on localhost

Oh, thanks^^
