### ISSUE TITLE
ERR_UNHANDLED_REJECTION Error 

### ISSUE THREAD

**Issue by AhmadShkour71** [RileCraft/DiscordBot-Template#44]
**Describe the issue**
iam use rainway host and he is perfect 
but sometimes show this error idk why

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
code: 'ERR_UNHANDLED_REJECTION'
}

he say in promise so iam think because slash halnder or what? 
iam try fix it but can't fixed

**Screenshots**
![Screenshot_20220330-153007_Chrome](https://user-images.githubusercontent.com/73717039/160846205-08ebc2aa-34fa-4e68-adb9-f5b73900493f.jpg)

**Comment by RileCraft** [comment]
Try other host or localhost and verify if same error occurs there as well.

**Comment by AhmadShkour71** [comment]
> uh idk tbh

ohh okay thx , iam will close issues
