### ISSUE TITLE
Select Menus won't respond.

### ISSUE THREAD

**Issue by Noxxe-0001** [RileCraft/DiscordBot-Template#46]
**Describe the issue**
Select menus won't respond when I create a new select menu and then create a new select menu with the name set as the customId for the select menu, I have read the documentation, it says that I can either put the custom ID of the select menu or one of the option values. When I put the value, it works, but when I use the custom ID it does not and I know your probably gonna say "Well just use the values" but I don't want to as it means I have to create like 13 different files for one command and I don't want to do that. Is it something that I am doing wrong, or is something that is wrong with code.

**Screenshots**
When I use the customId of the select menu, nothing happens. 
<img src="https://i.imgur.com/auDLmdd.png"></img>
-
This is the message action row with the select menu. 
<img src="https://i.imgur.com/zzm50bw.png"></img>
-
When I use the select menu with the custom id, nothing happens nothing is logged in the console.
[Link to the video](https://thumbs.gfycat.com/SatisfiedFarChanticleer-mobile.mp4)
**Host Details:**
 - OS: Windows 11
 - NodeJS Version: [v18.2.0]
 - Discord.JS Version: [v13.6.0]

**Additional context**
Is it something that I am doing wrong, or is it something wrong with the source code?

**Comment by RileCraft** [comment]
There was a small problem in `InteractionCreate` event file which only took selectMenu's customId when the other values were none. Found a solution to this.

**Comment by Noxxe-0001** [comment]
Cheers dude!
