### ISSUE TITLE
Slash Command Not Load

### ISSUE THREAD

**Issue by X4UTEAM** [RileCraft/DiscordBot-Template#5]
**Describe the issue**
Slash Command not load

**Expected behavior**
Problem show with last update (before 8 hours)
iam test in test guild and active **guild command** iam mean like that ` guild:["my guild test"],`
and if add new command not load 

iam try delete bot after that made bot and inite to guild ,all slash command not loaded
iam check if invite with `applications.commands` and yep iam invite with this scope

before this update everything work 100%

thx for help

**Comment by RileCraft** [comment]
I am gonna assume this was fixed.
