### ISSUE TITLE
Make this an actual Github Template

### ISSUE THREAD

**Issue by CodeSpent** [RileCraft/DiscordBot-Template#52]
**Name of the feature**
Add this as a genuine Github Template rather than just a template repo to allow easier use.

**What will this feature do?**
Allow devs to click the "Use Template" button to clone a repository for their use.

**Additional context**
[Instructions on creating a template repository.](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

**Comment by RileCraft** [comment]
Done
