### ISSUE TITLE
Suggestion Request: Update about section

### ISSUE THREAD

**Issue by SwitchAlpha** [RileCraft/DiscordBot-Template#55]
**Updating About section of repo**
About section should be updated like this since D.js version is V14

A bot template with command , event , button , selectmenus , slashcommands , contextmenus handler and error handlers. Made in Discord.JS V14

**What will this feature do?**
Easier access to people in need.

**Additional context**
NaN

**Comment by RileCraft** [comment]
I thought i changed it thonk
