### ISSUE TITLE
Excute an owner command but its not the owner

### ISSUE THREAD

**Issue by Kawet00** [RileCraft/DiscordBot-Template#56]
**Describe the issue**
When a member thats not a developer exceute a developers command like `eval`, it excute the command and after it send the message for ownerOnly. I have not errors

**To Reproduce**
I don't know what I changed

**Expected behavior**
don't execute the command

**Screenshots**
<img src="https://i.gyazo.com/b27f5616113c9d1bdf2aaf317478e947.png">
<img src="https://i.gyazo.com/28425e9f14305cc291430a8183334103.png">

**Host Details:**
 - OS: Windows 11
 - NodeJS Version: 18.12.1

**Additional context**
I test with the template so I change nothing in the conde just the Config.js and it work and I changed the messageCreate with the original and it dosen't work too so, it don't execute the command. So I need to know where I need to look for execute the loadCommandOption and after the command

**Comment by RileCraft** [comment]
Never seen this happen before.
You can find all the commandOption files in `Structures/CommandOptions`.

I'm not really sure what caused this but if it keeps happening then i would suggest to for some time manually create an owner only if() condition.

**Comment by Elpistolero131** [comment]
ok but you know where in the project why load the command with the option so load the options AND AFTER the command

**Comment by RileCraft** [comment]
Not sure right now what causing the problem but i will try to fix it soon
