### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by AhmadShkour71** [RileCraft/DiscordBot-Template#6]
first thx for new big update
it is nice and eazy to read and learn

**Describe the issue**
**1.**
eval command if use button he will show this error and not delete button
![Screenshot 2021-12-01 020858](https://user-images.githubusercontent.com/73717039/144148141-21911a64-5141-456b-a2a3-e7208d7c451e.png)
![Screenshot 2021-12-01 020907](https://user-images.githubusercontent.com/73717039/144148143-fbb80ba2-323f-4f76-a2dc-df3c9ad79114.png)

**2.** 
bot not load in console log ... but bot it running iam ..test ping command and he run
but in console log not show anything

**3.** 
iam made command and add **userPermissions** but he tell me not have permmison
and iam owner server hhhhh
![Screenshot 2021-12-01 035834](https://user-images.githubusercontent.com/73717039/144158017-80286c2f-0b67-485b-9975-9db79ba38310.png)
![Screenshot 2021-12-01 035844](https://user-images.githubusercontent.com/73717039/144158021-cbe12691-eafe-43a0-9a1e-2328cf29d3f4.png)

**Comment by RileCraft** [comment]
Thanks for feedback.
(1) I forgot to add the evalButton.js for the button.
(2) I cannot recreate this error so it maybe your host issue.
(3) Fixed in 4.0.1

**Comment by AhmadShkour71** [comment]
> @RileCraft 

Okay bro take your time
if see any bugs iam will send here

**Comment by RileCraft** [comment]
Eh i accidently leaked the token but ignore it.

Also the new update should fix the logging issue and make sure to use `npm start`.

I have tested cooldown and it worked fine for me.

**Comment by AhmadShkour71** [comment]
> @RileCraft 
okay now it fixed cooldown
iam use already npm start or node .


but Is it normal for him to appear like this?
because iam think it show number slash commands and events...
![Screenshot 2021-12-01 065743](https://user-images.githubusercontent.com/73717039/144174554-01e6323a-71a4-4828-b2c5-2e6ac02e2409.png)

**Comment by RileCraft** [comment]
it should log all the stuff
i mean it does for me
