### ISSUE TITLE
Docs domain expired It will be good idea hosting on github pages

### ISSUE THREAD

**Issue by SwitchAlpha** [RileCraft/DiscordBot-Template#60]
**Host on github pages rather than personel website**
Hosting docs on [Github Pages](https://pages.github.com/) will be good due to expired domain.

**What will this feature do?**
It will make docs available again and also cut the cost of domain and hosting.

**Additional context**
-

**Comment by RileCraft** [comment]
In the next update i might add docs as .md files in the repository itself as we don't really need a seperate site for few command option docs

**Comment by SwitchAlpha** [comment]
There is a docs branch but I think website looks better

**Comment by RileCraft** [comment]
The docs branch is the gitbook repo and point is why even need a seperate docs site as its very small documentation
