### ISSUE TITLE
Make (/) Command Time Out

### ISSUE THREAD

**Issue by abdalla-3077** [RileCraft/DiscordBot-Template#68]
**Look Like Normal Message Time Out**

**Comment by RileCraft** [comment]
What.

**Comment by brandonbayliss8** [comment]
I think he means , a cooldown like you have on normal messages but in Slash command format .

**Comment by abdalla-3077** [comment]
> I think he means , a cooldown like you have on normal messages but in Slash command format .

Exactly

**Comment by Noxxe-0001** [comment]
@abdalla-3077 You can use the 'GlobalCooldown' option on the command, and when the user runs that command, depending on the cooldown time set, they won't be able to run that command in any server until the timer runs out.
