### ISSUE TITLE
User Options

### ISSUE THREAD

**Issue by ToddyTheNoobDud** [RileCraft/DiscordBot-Template#71]
**Name of the feature**
User Options, String Options

**What will this feature do?**
i don't know if it exist buts its like d.js slashcommandbuilder, like .addstringoption(), .adduseroption()
**Additional context**
if it already exist tell me on how to do use it

**Comment by MarcZX100** [comment]
Yeah, it does exist. 
```js
command blah blah...,

options: [
      {
        name: 'user',
        description: 'The selected user.',
        type: ApplicationCommandOptionType.User,
        required: true
      }
],

run: async(client, interaction) => { blah blah....
```

**Comment by ToddyTheNoobDud** [comment]
thanks for letting me know, its one of my firts times using handlers that use Applicationcommandtype, etc

**Comment by MarcZX100** [comment]
Yeah no problem, I also came back from a long time and it's kind of difficult to keep up
