### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by ToddyTheNoobDud** [RileCraft/DiscordBot-Template#72]
**Name of the feature**
Eg: Mongo DB support

**What will this feature do?**
it will support database to save level system, warn, etc

**Additional context**

**Comment by MarcZX100** [comment]
I completely agree. Almost every single bot I've ever made required some database and the one I used was Mongo DB with mongoose. I used this template once and I had to kind of implement it easily, but probably not in the optimal way. If it was already implemented, it would be great. Theres no need to create a whole new model to cover all aspects the database could make use of, only with a simple one that saves a text written by the user may be enough.

**Comment by RileCraft** [comment]
I intentionally didn't use MongoDB as default as i wanted this template to allow users to clone it and use it instantly with minimial setup, if they want MongoDB they are capable to set it up themself and it will take hardly any changes to set it up and quick.db isn't too much integrated into the template and as always it is just a base template to start at.

**Comment by ToddyTheNoobDud** [comment]
alr, i set up it myself and it worked.
