### ISSUE TITLE
[ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

### ISSUE THREAD

**Issue by GoldO-dev** [RileCraft/DiscordBot-Template#82]
**Describe the issue**
When trying to install the newest version I get a ERR_UNSUPPORTED_ESM_URL_SCHEME error. I just followed the install guide in the readme

**To Reproduce**
1. Download the zip file from releases or from github with the code button 
2. Extract the zip file
3. Open the folder
4. Open a new terminal (If using VS Code)
5. Type npm install
6. Open the src folder
7. Open the config.js file
8. Change "Bot Prefix" to the prefix you want (I typed "!")
9. Change "Bot Token" to your bot's token
10. Change "Bot Owner Discord ID" to you discord ID
11. Type node . in the terminal

**Expected behavior**
I would extect the bot to start, but I got an error.

**Screenshots**
_Screenshot of the error:_
![ERR_UNSUPPORTED_ESM_URL_SCHEME error](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/19153f04-5859-4756-a6ca-92bcd334cf5f)
_Screenshot of my package.json file:_
![Package json file](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/ef36c2b0-c580-4d77-ac56-ba11e9ee1639)
_Screenshot of the return I got when I ran the npm install command (I know it can't be used to anything but attached it anyway):_
![npm install return](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/208bcc27-4d0f-414b-aeba-86d900cde2ef)

**Host Details:**
 - OS: Windows 10
 - NodeJS Version: 21.6.1

**Comment by RileCraft** [comment]
Can you try `node bot.js`

**Comment by GoldO-dev** [comment]
> Can you try `node bot.js`

I got the same error.
![image](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/8fd831a8-a211-4d67-8d4a-b7db60a40681)

**Comment by RileCraft** [comment]
In the bot.js file where `const __dirname` is, just put the value `import.meta.url` and see if it works

**Comment by GoldO-dev** [comment]
> In the bot.js file where `const __dirname` is, just put the value `import.meta.url` and see if it works

It didn't give any error, and the bot started, but the /ping doesn't work, same with the !ping

![image](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/b65c5cfd-a054-4c43-9f26-9714542295fa)
![image](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/54c50ea0-dd9e-4f6f-a938-4bc3b53cdb5d)
![image](https://github.com/RileCraft/DiscordBot-Template/assets/83804899/1b857502-40dd-45b6-b392-21841ea1ba64)

**Comment by RileCraft** [comment]
I have found a solution and will shortly push the fix.

**Comment by GoldO-dev** [comment]
Thanks. Appreciate the quick work.

Is there some docs for the template some where?

**Comment by GoldO-dev** [comment]
With docs I'm refering to a gitbook or something like that, so you don't need to click on the links every time.

**Comment by RileCraft** [comment]
I have pushed the update to `Unstable` branch and let me know if it works for you now.
I might consider gitbook or something else but a non-priority right now.

**Comment by GoldO-dev** [comment]
> I have pushed the update to `Unstable` branch and let me know if it works for you now.
> I might consider gitbook or something else but a non-priority right now.


Okay, will test it when I'm home in about 45 minutes.
