### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by gelones** [RileCraft/DiscordBot-Template#9]
when I run a slash command it gives this error on the terminal,

It doesn't always happen, sometimes the command works normally, but other times it doesn't work and this error occurs in the terminal.

```

[Error Mensagem] DiscordAPIError: Unknown interaction
[Error Localização] at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:349:13)

```

**Comment by RileCraft** [comment]
(1) Maybe host lag issue.
(2) Try removing the errorHandler event so you can see more information about the error.
(3) Make sure you are on latest version of handler as i haven't gotten this error yet.
